version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_demo
    environment:
      POSTGRES_DB: demo_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ismoil_0709
    ports:
      - "5433:5432"  # Expose container's default port 5432 to host's port 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: demo_bot_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_demo:5432/demo_bot_db  # Match the updated application.yml
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ismoil_0709
    depends_on:
      - postgres
    ports:
      - "80:80"

volumes:
  postgres-data:

